export const flavors = [
	'Vanilla',
	'Chocolate',
	'Strawberry',
	'Mint Chocolate Chip',
	'Cookies and Cream',
	'Rocky Road',
	'Pistachio',
	'Neapolitan',
	'Butter Pecan',
	'Salted Caramel',
	'Coffee',
	'Mango',
	'Raspberry Ripple',
	'Lemon Sorbet',
	'Green Tea',
	'Coconut',
	'Black Cherry',
	'Banana',
	'Almond Fudge',
	'Cinnamon',
	'Blueberry Cheesecake',
	'Tiramisu',
	'Red Velvet',
	'Matcha',
	'Peanut Butter Cup',
	'Cookie Dough',
	'Rum Raisin',
	'Birthday Cake',
	'Lychee',
	'Honey Lavender',
];
